[package]
name = "observer-wal"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
bytes.workspace = true
crc32c.workspace = true
observer-protocol = { path = "../observer-protocol" }

[dev-dependencies]
tempfile = "3"

[lints]
workspace = true
