//! OpenTelemetry wire types and Observer protocol definitions.

pub mod ingestion;

pub use ingestion::{AcceptedBatch, AppendError, AppendErrorKind, IngestSink, Signal};

/// Published OpenTelemetry Protocol types generated by `opentelemetry-proto`.
pub mod otlp {
    pub use opentelemetry_proto::tonic::collector::logs::v1::{
        ExportLogsServiceRequest, ExportLogsServiceResponse,
        logs_service_client::LogsServiceClient,
        logs_service_server::{LogsService, LogsServiceServer},
    };
    pub use opentelemetry_proto::tonic::common::v1::{AnyValue, KeyValue, any_value};
    pub use opentelemetry_proto::tonic::logs::v1::ResourceLogs;
    pub use opentelemetry_proto::tonic::resource::v1::Resource;
}
